name: Action CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

jobs:
  Windows-x64:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'
          cache: 'gradle'

      - name: Build
        run: ./gradlew createReleaseDistributable

      - name: Upload UpdaterKMM windows-x86_64-exe
        uses: actions/upload-artifact@v4
        with:
          name: UpdaterKMM-windows-x86_64-exe
          path: composeApp/build/compose/binaries/main-release/app/UpdaterKMM
          compression-level: 9

  macOS-arm64:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'
          cache: 'gradle'

      - name: Build
        run: |
          ./gradlew packageReleaseDistributionForCurrentOS
          xcodebuild -project iosApp/iosApp.xcodeproj -scheme iosApp -sdk iphonesimulator -configuration Debug build

      - name: Upload UpdaterKMM darwin-aarch64-dmg
        uses: actions/upload-artifact@v4
        with:
          name: UpdaterKMM-darwin-aarch64-dmg
          path: composeApp/build/compose/binaries/main-release/dmg
          compression-level: 9

      - name: Upload UpdaterKMM ios-aarch64-app
        uses: actions/upload-artifact@v4
        with:
          name: UpdaterKMM-ios-aarch64-app
          path: /Users/runner/Library/Developer/Xcode/DerivedData/iosApp-*/Build/Products/Debug-iphonesimulator
          compression-level: 9

  Linux-x64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'
          cache: 'gradle'

      - name: Build
        run: |
          bash ./gradlew packageReleaseDistributionForCurrentOS
          bash ./gradlew createReleaseDistributable
          bash ./gradlew assembleRelease

      - name: Upload UpdaterKMM linux-x86_64-deb
        uses: actions/upload-artifact@v4
        with:
          name: UpdaterKMM-linux-x86_64-deb
          path: composeApp/build/compose/binaries/main-release/deb
          compression-level: 9

      - name: Upload UpdaterKMM linux-x86_64-other
        uses: actions/upload-artifact@v4
        with:
          name: UpdaterKMM-linux-x86_64-other
          path: composeApp/build/compose/binaries/main-release/app/UpdaterKMM
          compression-level: 9

      - name: Upload UpdaterKMM android-aarch64-apk
        uses: actions/upload-artifact@v4
        with:
          name: UpdaterKMM-android-aarch64-apk
          path: composeApp/build/outputs/apk/release
          compression-level: 9
