name: Action CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

jobs:
  Windows-x64:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Build Windows platform
        run: ./gradlew createReleaseDistributable

      - name: Upload UpdaterKMP windows-x86_64-exe
        uses: actions/upload-artifact@v4
        with:
          name: UpdaterKMP-windows-x86_64-exe
          path: composeApp/build/compose/binaries/main-release/app/Updater
          compression-level: 9

  macOS-arm64:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'
          cache: 'gradle'

      - name: Build Darwin platform
        run: ./gradlew packageReleaseDistributionForCurrentOS

      - name: Upload UpdaterKMP darwin-aarch64-dmg
        uses: actions/upload-artifact@v4
        with:
          name: UpdaterKMP-darwin-aarch64-dmg
          path: composeApp/build/compose/binaries/main-release/dmg
          compression-level: 9

  Linux-x64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'
          cache: 'gradle'


      - name: Build Android platform
        run: |
          echo ${{ secrets.SIGNING_KEY }} | base64 -d > keystore.jks
          bash ./gradlew assembleRelease
        env:
          KEYSTORE_PATH: "../keystore.jks"
          KEYSTORE_PASS: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Upload UpdaterKMP android-aarch64-apk
        uses: actions/upload-artifact@v4
        with:
          name: UpdaterKMP-android-aarch64-apk
          path: composeApp/build/outputs/apk/release
          compression-level: 9

      - name: Build Linux platform
        run: |
          bash ./gradlew packageReleaseDistributionForCurrentOS
          bash ./gradlew createReleaseDistributable

      - name: Upload UpdaterKMP linux-x86_64-deb
        uses: actions/upload-artifact@v4
        with:
          name: UpdaterKMP-linux-x86_64-deb
          path: composeApp/build/compose/binaries/main-release/deb
          compression-level: 9

      - name: Upload UpdaterKMP linux-x86_64-other
        uses: actions/upload-artifact@v4
        with:
          name: UpdaterKMP-linux-x86_64-other
          path: composeApp/build/compose/binaries/main-release/app/Updater
          compression-level: 9

